# .github/workflows/ci.yml
name: CI

on:
  push: { branches: [ main ] }
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: src/academo } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: 21, cache: maven }
      - name: Unit tests (H2)
        run: |
          rm -rf target
          mvn -B clean test \
            -Dgroups=unit -DexcludedGroups=db \
            -Dspring.profiles.active=unit \
            -Dallure.results.directory=target/allure-results
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-reports
          path: |
            src/academo/target/surefire-reports
            src/academo/target/allure-results

  db:
    needs: unit
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: src/academo } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: 21, cache: maven }
      - name: DB tests (H2 classic)
        run: |
          rm -rf target/allure-results target/site/allure-maven-plugin
          mvn -B test -Dgroups=db -Dspring.profiles.active=unit \
             -Dallure.results.directory=target/allure-results
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: db-reports
          path: |
            src/academo/target/surefire-reports
            src/academo/target/allure-results

  e2e:
    needs: db
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: src/academo } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: 21, cache: maven }

      - name: Docker info
        run: |
          docker version
          docker info || true

      - name: E2E (Testcontainers + Postgres)
        env:
          TESTCONTAINERS_RYUK_DISABLED: "true"
          TESTCONTAINERS_CHECKS_DISABLE: "true"
          DOCKER_HOST: unix:///var/run/docker.sock
        run: |
          mvn -B clean test-compile \
             -Dit.test=MvpE2EITCase \
             failsafe:integration-test failsafe:verify

      - name: List containers
        if: always()
        run: docker ps -a

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-reports
          path: |
            src/academo/target/failsafe-reports
            src/academo/target/e2e-http.log
            src/academo/target/testcontainers/*log
  
