name: CI
on:
  push: { branches: [ main ] }
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/academo   # <-- change if your pom.xml is elsewhere
    steps:
      - uses: actions/checkout@v4

      - name: JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Unit tests (H2)
        run: |
          rm -rf target
          mvn -B clean test \
            -Dgroups=unit -DexcludedGroups=db \
            -Dspring.profiles.active=unit

      - name: DB tests (H2 classic)
        run: |
          rm -rf target/allure-results target/site/allure-maven-plugin || true
          mvn -B test -Dgroups=db -Dspring.profiles.active=unit

      - name: E2E tests
        run: |
          mvn -B -Dit.test=MvpE2EITCase failsafe:integration-test failsafe:verify
