name: CI
on:
  push: { branches: [ main ] }
  pull_request:

jobs:
  tests-with-maven-image:
    runs-on: ubuntu-latest
    env:
      WS: ${{ github.workspace }}
      PROJECT_DIR: src/academo
    steps:
      - uses: actions/checkout@v4

      - name: Cache Maven repo (host)
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      # ============ UNIT ============
      - name: UNIT tests (H2)
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "$HOME/.m2:/root/.m2" \
            -v "$WS:$WS" \
            -w "$WS/$PROJECT_DIR" \
            maven:3.9.9-eclipse-temurin-21 \
            mvn -B clean test -Dgroups=unit -DexcludedGroups=db -Dspring.profiles.active=unit

      # ============= DB =============
      - name: DB tests (H2 classic)
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "$HOME/.m2:/root/.m2" \
            -v "$WS:$WS" \
            -w "$WS/$PROJECT_DIR" \
            maven:3.9.9-eclipse-temurin-21 \
            mvn -B test -Dgroups=db -Dspring.profiles.active=unit

      # ============= E2E ============
      - name: E2E tests (Failsafe + Testcontainers)
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "$HOME/.m2:/root/.m2" \
            -v "$WS:$WS" \
            -w "$WS/$PROJECT_DIR" \
            maven:3.9.9-eclipse-temurin-21 \
            bash -lc 'mvn -B -Dit.test=MvpE2EITCase failsafe:integration-test failsafe:verify'
