name: CI - unit → db → e2e

on:
  push:
  pull_request:
  workflow_dispatch: {}   # lets you trigger it manually from the Actions tab

defaults:
  run:
    working-directory: src/academo

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Unit tests (H2)
        run: |
          mvn -B clean test \
            -Dspring.profiles.active=unit \
            -Dgroups=unit -DexcludedGroups=db \
            -Dallure.results.directory=target/allure-results

      - name: Upload unit reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-reports
          path: |
            src/academo/target/surefire-reports/**
            src/academo/target/allure-results/**

  db:
    runs-on: ubuntu-latest
    needs: unit
    steps:
      - uses: actions/checkout@v4

      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Classic DB tests (H2-in-mem)
        run: |
          mvn -B test \
            -Dspring.profiles.active=unit \
            -Dgroups=db \
            -Dallure.results.directory=target/allure-results

      - name: Upload db reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: db-reports
          path: |
            src/academo/target/surefire-reports/**
            src/academo/target/allure-results/**

  e2e:
    runs-on: ubuntu-latest
    needs: db
    env:
      TESTCONTAINERS_CHECKS_DISABLE: "true"
      TESTCONTAINERS_RYUK_DISABLED: "true"
      DOCKER_BUILDKIT: "1"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: E2E Integration tests (Postgres Testcontainers)
        run: |
          mvn -B clean test-compile \
            -Dit.test=MvpE2EITCase \
            failsafe:integration-test failsafe:verify

      - name: Upload e2e reports & logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-reports
          path: |
            src/academo/target/failsafe-reports/**
            src/academo/target/e2e-http.log
