name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: 'temurin', java-version: '21' }
      - name: Unit tests (H2)
        run: |
          mvn -B clean test \
            -Dspring.profiles.active=unit \
            -Dgroups=unit -DexcludedGroups=db \
            -Dallure.results.directory=target/allure-results
      - name: Upload surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-unit
          path: target/surefire-reports

  integration:
    runs-on: ubuntu-latest
    needs: unit
    if: ${{ success() }}   # skip if unit failed
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: 'temurin', java-version: '21' }
      - name: Classic integration (H2)
        run: |
          mvn -B test \
            -Dspring.profiles.active=unit \
            -Dgroups=db \
            -Dallure.results.directory=target/allure-results
      - name: Upload surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-integration
          path: target/surefire-reports

  e2e:
    runs-on: ubuntu-latest
    needs: integration
    if: ${{ success() }}   # skip if integration failed
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: 'temurin', java-version: '21' }
      - name: Enable Docker (for Testcontainers)
        uses: docker/setup-buildx-action@v3
      - name: E2E (failsafe; Testcontainers Postgres)
        run: |
          mvn -B clean test-compile \
            -Dit.test=MvpE2EITCase \
            failsafe:integration-test failsafe:verify
      - name: Upload failsafe + logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-artifacts
          path: |
            target/failsafe-reports
            target/e2e-http.log
